baseUrl = "https://davidnix.io/"
languageCode = "en-us"
title = "David Nix's Blog - Tutorials, Opinions, Rants"
disqusShortname = "davidnix"
paginate = 10
canonifyurls = true

[params]

	title = "David Nix"
	subtitle = "Startup Software Developer, Go and iOS"
	copyright = ""

	# You can choose between green, orange, red and blue.
	themeColor = "blue"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "David Nix"
	bio = "iOS developer since 2010. Backend web developer since 2012. For new posts, follow me on [twitter](https://twitter.com/@davidnix_) or subscribe to the RSS feed."
	description = "David Nix's Blog"
	location = "Denver, CO" # optional
	twitter = "@davidnix_" # optional
	github = "DavidNix" # optional
	linkedin = "nixdavid" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "Aw shucks, page not found. :-("
